/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package wicadi;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStreamReader;

/**
 *
 * @author Kalana Hettiarachchi
 */
import java.util.LinkedList;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.filechooser.FileSystemView;

public class MAIN extends javax.swing.JFrame {

    StringBuffer s;
    Random r;
    sc4 sc;
    double zx = 0;
    JFrame gw;
    JFrame gw2;
    JTextArea ta;
    grafer grf;
    LinkedList<String> lis;
    private int xp = 5;

    public MAIN() {

        sc = new sc4();
        r = new Random();
        s = new StringBuffer();
        lis = new LinkedList<String>();
        gw = new JFrame("Graph");
        gw2 = new JFrame();
        gw.setBounds(100, 100, 500, 500);
        gw2.setBounds(100, 100, 500, 500);
        ta = new JTextArea();
        JScrollPane pp = new JScrollPane();
        pp.setViewportView(ta);
        gw2.getContentPane().add(pp);
        grf = new grafer();
        gw.setContentPane(grf);
        

        initComponents();
        this.jTextField1.setEditable(true);
        setSize(830,400);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        number1btn = new javax.swing.JButton();
        number2btn = new javax.swing.JButton();
        number3btn = new javax.swing.JButton();
        number4btn = new javax.swing.JButton();
        number5btn = new javax.swing.JButton();
        number6btn = new javax.swing.JButton();
        number7btn = new javax.swing.JButton();
        number8btn = new javax.swing.JButton();
        number9btn = new javax.swing.JButton();
        number0btn = new javax.swing.JButton();
        plusbutton = new javax.swing.JButton();
        minusbutton = new javax.swing.JButton();
        mulltiplybutton = new javax.swing.JButton();
        dividebutton = new javax.swing.JButton();
        answerbutton = new javax.swing.JButton();
        sqrtbutton = new javax.swing.JButton();
        cosbutton = new javax.swing.JButton();
        tanbutton = new javax.swing.JButton();
        powerbutton = new javax.swing.JButton();
        expbutton = new javax.swing.JButton();
        lnbutton = new javax.swing.JButton();
        openbracket = new javax.swing.JButton();
        closebracket = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        xbutton = new javax.swing.JButton();
        clearbutton = new javax.swing.JButton();
        arsbutton = new javax.swing.JButton();
        arcbutton = new javax.swing.JButton();
        artbutton = new javax.swing.JButton();
        dotdutton = new javax.swing.JButton();
        sigbutton = new javax.swing.JButton();
        savebutton = new javax.swing.JButton();
        loadbutton = new javax.swing.JButton();
        deletebutton = new javax.swing.JButton();
        valueofx = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        logbutton = new javax.swing.JButton();
        jButton56 = new javax.swing.JButton();
        stepbutton = new javax.swing.JButton();
        clearsavebutton = new javax.swing.JButton();
        roots = new javax.swing.JButton();
        differentiation = new javax.swing.JButton();
        intergration = new javax.swing.JButton();
        graphbutton = new javax.swing.JButton();
        jButton48 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        rembutton = new javax.swing.JButton();
        pibutton = new javax.swing.JButton();
        sinbutton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        history = new javax.swing.JTextArea();
        clearhistory = new javax.swing.JButton();
        saveformula = new javax.swing.JButton();
        loadformula = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("WiCaDi");
        setBounds(new java.awt.Rectangle(0, 0, 816, 400));
        setMinimumSize(new java.awt.Dimension(530, 700));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        number1btn.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        number1btn.setText("1");
        number1btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number1btnActionPerformed(evt);
            }
        });
        getContentPane().add(number1btn);
        number1btn.setBounds(10, 260, 50, 32);

        number2btn.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        number2btn.setText("2");
        number2btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number2btnActionPerformed(evt);
            }
        });
        getContentPane().add(number2btn);
        number2btn.setBounds(70, 260, 50, 32);

        number3btn.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        number3btn.setText("3");
        number3btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number3btnActionPerformed(evt);
            }
        });
        getContentPane().add(number3btn);
        number3btn.setBounds(130, 260, 50, 32);

        number4btn.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        number4btn.setText("4");
        number4btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number4btnActionPerformed(evt);
            }
        });
        getContentPane().add(number4btn);
        number4btn.setBounds(190, 260, 50, 32);

        number5btn.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        number5btn.setText("5");
        number5btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number5btnActionPerformed(evt);
            }
        });
        getContentPane().add(number5btn);
        number5btn.setBounds(250, 260, 50, 32);

        number6btn.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        number6btn.setText("6");
        number6btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number6btnActionPerformed(evt);
            }
        });
        getContentPane().add(number6btn);
        number6btn.setBounds(10, 290, 50, 32);

        number7btn.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        number7btn.setText("7");
        number7btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number7btnActionPerformed(evt);
            }
        });
        getContentPane().add(number7btn);
        number7btn.setBounds(70, 290, 50, 32);

        number8btn.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        number8btn.setText("8");
        number8btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number8btnActionPerformed(evt);
            }
        });
        getContentPane().add(number8btn);
        number8btn.setBounds(130, 290, 50, 32);

        number9btn.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        number9btn.setText("9");
        number9btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number9btnActionPerformed(evt);
            }
        });
        getContentPane().add(number9btn);
        number9btn.setBounds(190, 290, 50, 32);

        number0btn.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        number0btn.setText("0");
        number0btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number0btnActionPerformed(evt);
            }
        });
        getContentPane().add(number0btn);
        number0btn.setBounds(250, 290, 50, 32);

        plusbutton.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        plusbutton.setText("+");
        plusbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(plusbutton);
        plusbutton.setBounds(10, 320, 50, 32);

        minusbutton.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        minusbutton.setText("-");
        minusbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minusbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(minusbutton);
        minusbutton.setBounds(70, 320, 50, 32);

        mulltiplybutton.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        mulltiplybutton.setText("*");
        mulltiplybutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mulltiplybuttonActionPerformed(evt);
            }
        });
        getContentPane().add(mulltiplybutton);
        mulltiplybutton.setBounds(130, 320, 50, 32);

        dividebutton.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        dividebutton.setText("/");
        dividebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dividebuttonActionPerformed(evt);
            }
        });
        getContentPane().add(dividebutton);
        dividebutton.setBounds(190, 320, 50, 32);

        answerbutton.setText("ANS");
        answerbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(answerbutton);
        answerbutton.setBounds(180, 530, 120, 32);

        sqrtbutton.setText("√");
        sqrtbutton.setToolTipText("Sin");
        sqrtbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sqrtbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(sqrtbutton);
        sqrtbutton.setBounds(240, 410, 60, 32);

        cosbutton.setText("Cos");
        cosbutton.setToolTipText("Cos");
        cosbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cosbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(cosbutton);
        cosbutton.setBounds(10, 450, 70, 32);

        tanbutton.setText("Tan");
        tanbutton.setToolTipText("Tan");
        tanbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tanbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(tanbutton);
        tanbutton.setBounds(10, 490, 70, 32);

        powerbutton.setText("^");
        powerbutton.setToolTipText("a^b a to power b");
        powerbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                powerbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(powerbutton);
        powerbutton.setBounds(180, 450, 50, 32);

        expbutton.setText("exp");
        expbutton.setToolTipText("exp(x) e^x");
        expbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(expbutton);
        expbutton.setBounds(240, 450, 60, 32);

        lnbutton.setText("ln");
        lnbutton.setToolTipText("log at base e");
        lnbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(lnbutton);
        lnbutton.setBounds(180, 490, 50, 32);

        openbracket.setText("(");
        openbracket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openbracketActionPerformed(evt);
            }
        });
        getContentPane().add(openbracket);
        openbracket.setBounds(90, 370, 40, 32);

        closebracket.setText(")");
        closebracket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closebracketActionPerformed(evt);
            }
        });
        getContentPane().add(closebracket);
        closebracket.setBounds(130, 370, 40, 32);

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jTextField1.setOpaque(false);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(10, 90, 490, 50);

        jTextField2.setEditable(false);
        jTextField2.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        jTextField2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jTextField2.setOpaque(false);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(320, 150, 180, 30);

        xbutton.setText("x");
        xbutton.setToolTipText("Variable");
        xbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(xbutton);
        xbutton.setBounds(180, 370, 120, 32);

        clearbutton.setText("CLR");
        clearbutton.setToolTipText("Clear Screen");
        clearbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(clearbutton);
        clearbutton.setBounds(210, 190, 70, 20);

        arsbutton.setText("Ars");
        arsbutton.setToolTipText("Sin Inverse");
        arsbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arsbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(arsbutton);
        arsbutton.setBounds(90, 410, 80, 32);

        arcbutton.setText("Arc");
        arcbutton.setToolTipText("Cos Inverse");
        arcbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arcbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(arcbutton);
        arcbutton.setBounds(90, 450, 80, 32);

        artbutton.setText("Art");
        artbutton.setToolTipText("Tan Inverse");
        artbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                artbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(artbutton);
        artbutton.setBounds(90, 490, 80, 32);

        dotdutton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        dotdutton.setText(".");
        dotdutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dotduttonActionPerformed(evt);
            }
        });
        getContentPane().add(dotdutton);
        dotdutton.setBounds(250, 320, 50, 31);

        sigbutton.setText("Sig");
        sigbutton.setToolTipText("Signum f(x)");
        sigbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sigbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(sigbutton);
        sigbutton.setBounds(90, 530, 80, 32);

        savebutton.setText("SAVE");
        savebutton.setToolTipText("Save result in List");
        savebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebuttonActionPerformed(evt);
            }
        });
        getContentPane().add(savebutton);
        savebutton.setBounds(10, 220, 80, 20);

        loadbutton.setText("LOAD");
        loadbutton.setToolTipText("Load a value from list");
        loadbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(loadbutton);
        loadbutton.setBounds(10, 190, 80, 20);

        deletebutton.setText("DEL");
        deletebutton.setToolTipText("Delet a character");
        deletebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebuttonActionPerformed(evt);
            }
        });
        getContentPane().add(deletebutton);
        deletebutton.setBounds(210, 220, 70, 20);

        valueofx.setText("Value of (X)");
        valueofx.setToolTipText("Value of function at x");
        valueofx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valueofxActionPerformed(evt);
            }
        });
        getContentPane().add(valueofx);
        valueofx.setBounds(320, 490, 120, 30);

        jButton39.setText("Abs");
        jButton39.setToolTipText("Absolute value");
        jButton39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton39ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton39);
        jButton39.setBounds(10, 370, 70, 32);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("WiCaDi");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });
        getContentPane().add(jLabel1);
        jLabel1.setBounds(660, 0, 160, 40);

        logbutton.setText("Log");
        logbutton.setToolTipText("log at base 10");
        logbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(logbutton);
        logbutton.setBounds(240, 490, 60, 32);

        jButton56.setText("ABOUT");
        jButton56.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton56ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton56);
        jButton56.setBounds(560, 30, 100, 20);

        stepbutton.setText("Step");
        stepbutton.setToolTipText("Set no of digit after decimal point");
        stepbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stepbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(stepbutton);
        stepbutton.setBounds(100, 190, 100, 20);

        clearsavebutton.setText("CLR SAVE");
        clearsavebutton.setToolTipText("Empty list");
        clearsavebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearsavebuttonActionPerformed(evt);
            }
        });
        getContentPane().add(clearsavebutton);
        clearsavebutton.setBounds(100, 220, 100, 20);

        roots.setText("ROOTS");
        roots.setToolTipText("Roots in a given Interval");
        roots.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rootsActionPerformed(evt);
            }
        });
        getContentPane().add(roots);
        roots.setBounds(320, 370, 160, 32);

        differentiation.setText("DIFFERENTIATION");
        differentiation.setToolTipText("Aprox Differentiation");
        differentiation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                differentiationActionPerformed(evt);
            }
        });
        getContentPane().add(differentiation);
        differentiation.setBounds(320, 410, 160, 32);

        intergration.setText("INTEGRATION");
        intergration.setToolTipText("Aprox Integration");
        intergration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intergrationActionPerformed(evt);
            }
        });
        getContentPane().add(intergration);
        intergration.setBounds(320, 450, 160, 32);

        graphbutton.setText("GRAPH");
        graphbutton.setToolTipText("Make Graf of function");
        graphbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                graphbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(graphbutton);
        graphbutton.setBounds(320, 260, 90, 32);

        jButton48.setText("CENTRE");
        jButton48.setToolTipText("Set centre for graf");
        jButton48.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton48ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton48);
        jButton48.setBounds(320, 300, 90, 32);

        jButton24.setText("PIX");
        jButton24.setToolTipText("Set Pixel per unit of graf");
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton24);
        jButton24.setBounds(430, 260, 60, 32);

        jCheckBox1.setText("GRID");
        jCheckBox1.setToolTipText("Grid display");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox1);
        jCheckBox1.setBounds(430, 300, 70, 24);

        rembutton.setText("Rem");
        rembutton.setToolTipText(" g(x) reminder f(x)");
        rembutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rembuttonActionPerformed(evt);
            }
        });
        getContentPane().add(rembutton);
        rembutton.setBounds(10, 530, 70, 32);

        pibutton.setText("pi");
        pibutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pibuttonActionPerformed(evt);
            }
        });
        getContentPane().add(pibutton);
        pibutton.setBounds(180, 410, 50, 32);

        sinbutton.setText("Sin");
        sinbutton.setToolTipText("Sin");
        sinbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sinbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(sinbutton);
        sinbutton.setBounds(10, 410, 70, 32);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("History");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(530, 70, 120, 22);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(370, 60, 0, 2);
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(10, 60, 800, 10);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(510, 62, 10, 490);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("By SEMICOLON;");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(690, 40, 110, 16);

        history.setColumns(20);
        history.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        history.setRows(5);
        jScrollPane1.setViewportView(history);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(530, 110, 270, 400);

        clearhistory.setText("Clear History");
        clearhistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearhistoryActionPerformed(evt);
            }
        });
        getContentPane().add(clearhistory);
        clearhistory.setBounds(530, 530, 270, 32);

        saveformula.setText("Save Formula");
        saveformula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveformulaActionPerformed(evt);
            }
        });
        getContentPane().add(saveformula);
        saveformula.setBounds(320, 530, 120, 32);

        loadformula.setText("Load Formula");
        loadformula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadformulaActionPerformed(evt);
            }
        });
        getContentPane().add(loadformula);
        loadformula.setBounds(320, 570, 120, 32);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private static double round(double d, int k) {

           if(Double.isInfinite(d))
            {
                return d;
            }
                  
            double h1=d%1;
            double h2=(Math.round(h1*Math.pow(10, k)))/Math.pow(10, k);
            double h3=d-h1;
            double d1=h3+h2;
           
            return d1;

    }

    private void number1btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number1btnActionPerformed
        s = s.append("1");
        jTextField1.setText(s.toString());
    }//GEN-LAST:event_number1btnActionPerformed

    private void number2btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number2btnActionPerformed
        s = s.append("2");
        jTextField1.setText(s.toString());
    }//GEN-LAST:event_number2btnActionPerformed

    private void number3btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number3btnActionPerformed
        s = s.append("3");
        jTextField1.setText(s.toString());
    }//GEN-LAST:event_number3btnActionPerformed

    private void number4btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number4btnActionPerformed
        s = s.append("4");
        jTextField1.setText(s.toString());
    }//GEN-LAST:event_number4btnActionPerformed

    private void number5btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number5btnActionPerformed
        s = s.append("5");
        jTextField1.setText(s.toString());
    }//GEN-LAST:event_number5btnActionPerformed

    private void number6btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number6btnActionPerformed
        s = s.append("6");
        jTextField1.setText(s.toString());
    }//GEN-LAST:event_number6btnActionPerformed

    private void number7btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number7btnActionPerformed
        s = s.append("7");
        jTextField1.setText(s.toString());
    }//GEN-LAST:event_number7btnActionPerformed

    private void number8btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number8btnActionPerformed
        s = s.append("8");
        jTextField1.setText(s.toString());
    }//GEN-LAST:event_number8btnActionPerformed

    private void number9btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number9btnActionPerformed
        s = s.append("9");
        jTextField1.setText(s.toString());
    }//GEN-LAST:event_number9btnActionPerformed

    private void number0btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number0btnActionPerformed
        s = s.append("0");
        jTextField1.setText(s.toString());
    }//GEN-LAST:event_number0btnActionPerformed

    private void plusbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusbuttonActionPerformed
        s = s.append("+");
        jTextField1.setText(s.toString());
    }//GEN-LAST:event_plusbuttonActionPerformed

    private void minusbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minusbuttonActionPerformed
        s = s.append("-");
        jTextField1.setText(s.toString());
    }//GEN-LAST:event_minusbuttonActionPerformed

    private void mulltiplybuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mulltiplybuttonActionPerformed
        s = s.append("*");
        jTextField1.setText(s.toString());
    }//GEN-LAST:event_mulltiplybuttonActionPerformed

    private void dividebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dividebuttonActionPerformed
        s = s.append("/");
        jTextField1.setText(s.toString());
    }//GEN-LAST:event_dividebuttonActionPerformed

    private void answerbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerbuttonActionPerformed
        try {

            double d = round(sc.con(this.jTextField1.getText(), zx), xp);
            jTextField2.setText("" + d + " ");
            
            
            history.setText(history.getText() +"\n"+ jTextField1.getText()+" = "+jTextField2.getText());

        } catch (Exception dd) {
            jTextField2.setText("SYNTEX ERROR"+dd);

        }
       
    }//GEN-LAST:event_answerbuttonActionPerformed

    private void sqrtbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sqrtbuttonActionPerformed
        s = s.append("√");
        jTextField1.setText("√");
    }//GEN-LAST:event_sqrtbuttonActionPerformed

    private void cosbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cosbuttonActionPerformed
        s = s.append("Cos");
        jTextField1.setText(s.toString());
    }//GEN-LAST:event_cosbuttonActionPerformed

    private void tanbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tanbuttonActionPerformed
        s = s.append("Tan");
        jTextField1.setText(s.toString());
    }//GEN-LAST:event_tanbuttonActionPerformed

    private void powerbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_powerbuttonActionPerformed
        s = s.append("^");
        jTextField1.setText(s.toString());
    }//GEN-LAST:event_powerbuttonActionPerformed

    private void expbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expbuttonActionPerformed
        s = s.append("ep");
        jTextField1.setText(s.toString());
    }//GEN-LAST:event_expbuttonActionPerformed

    private void lnbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnbuttonActionPerformed
        s = s.append("ln");
        jTextField1.setText(s.toString());
    }//GEN-LAST:event_lnbuttonActionPerformed

    private void openbracketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openbracketActionPerformed
        s = s.append("(");
        jTextField1.setText(s.toString());
    }//GEN-LAST:event_openbracketActionPerformed

    private void closebracketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closebracketActionPerformed
        s = s.append(")");
        jTextField1.setText(s.toString());
    }//GEN-LAST:event_closebracketActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        jTextField1.setEditable(true);
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void xbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xbuttonActionPerformed
        s = s.append("x");
        jTextField1.setText(s.toString());
    }//GEN-LAST:event_xbuttonActionPerformed

    private void clearbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearbuttonActionPerformed
        s.delete(0, s.length());
        jTextField1.setText("");
        jTextField2.setText("");
    }//GEN-LAST:event_clearbuttonActionPerformed

    private void arsbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arsbuttonActionPerformed
        s = s.append("Ars");
        jTextField1.setText(s.toString());
    }//GEN-LAST:event_arsbuttonActionPerformed

    private void arcbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arcbuttonActionPerformed
        s = s.append("Arc");
        jTextField1.setText(s.toString());
    }//GEN-LAST:event_arcbuttonActionPerformed

    private void artbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_artbuttonActionPerformed
        s = s.append("Art");
        jTextField1.setText(s.toString());
    }//GEN-LAST:event_artbuttonActionPerformed

    private void dotduttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dotduttonActionPerformed
        s = s.append(".");
        jTextField1.setText(s.toString());
    }//GEN-LAST:event_dotduttonActionPerformed

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        //jLabel1.setForeground(new Color(r.nextInt(256), r.nextInt(256), r.nextInt(256)));
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        //jLabel1.setForeground(new Color(r.nextInt(256), r.nextInt(256), r.nextInt(256)));// TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseExited

    private void valueofxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valueofxActionPerformed
        try {
            zx = Double.parseDouble(JOptionPane.showInputDialog("Enter X"));
        } catch (Exception exception) {
            return;
        }


        this.answerbutton.doClick();
      
    }//GEN-LAST:event_valueofxActionPerformed

    private void savebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebuttonActionPerformed
        try {
            lis.add(this.jTextField2.getText());
            JOptionPane.showMessageDialog(this, "SAVED AT INDEX " + (lis.size() - 1), "", 2);
            //this.history.setText(lis.getFirst());
        } catch (Exception exception) {
            return;
        }

        
    }//GEN-LAST:event_savebuttonActionPerformed

    private void loadbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadbuttonActionPerformed
        try {
            int a = Integer.parseInt(JOptionPane.showInputDialog("ENTER INDEX"));
            s.append(lis.get(a));
            this.jTextField1.setText(s.toString());
        } catch (Exception exception) {
            return;
        }

      
      
    }//GEN-LAST:event_loadbuttonActionPerformed

    private void deletebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebuttonActionPerformed
        if (s.length() > 0) {
            s.deleteCharAt(s.length() - 1);
            jTextField1.setText(s.toString());
        }
      
    }//GEN-LAST:event_deletebuttonActionPerformed

    private void jButton39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton39ActionPerformed
        s = s.append("Abs");
        jTextField1.setText(s.toString());
    }//GEN-LAST:event_jButton39ActionPerformed

    private void stepbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stepbuttonActionPerformed
        try {
            xp = Integer.parseInt(JOptionPane.showInputDialog("Enter no of Digit after decimal point\n(Active from next operation)"));
        } catch (Exception exception) {
            return;
        }



    // TODO add your handling code here:
    }//GEN-LAST:event_stepbuttonActionPerformed

    private void clearsavebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearsavebuttonActionPerformed
        lis.clear();
    }//GEN-LAST:event_clearsavebuttonActionPerformed

    private void logbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logbuttonActionPerformed
        s = s.append("Log");
        jTextField1.setText(s.toString());
    // TODO add your handling code here:
    }//GEN-LAST:event_logbuttonActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        if (this.jCheckBox1.isSelected()) {
            grafer.p = true;
        } else {
            grafer.p = false;
        }
    // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jButton48ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton48ActionPerformed
        try {
            grafer.ofx = Double.parseDouble(JOptionPane.showInputDialog("Enter centre point x cordinate"));
            grafer.ofy = Double.parseDouble(JOptionPane.showInputDialog("Enter centre point y cordinate"));

        } catch (Exception exception) {
            return;
        }

        
    }//GEN-LAST:event_jButton48ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        try {
            int n = Integer.parseInt(JOptionPane.showInputDialog("Enter n - no of Pixel per unit\n 0<n<2000"));
            if (!(n > 0 && n < 2000)) {
                throw new Exception();
            }
            grafer.k = n;
        } catch (Exception exception) {
            return;
        }

    }//GEN-LAST:event_jButton24ActionPerformed

    private void rootsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rootsActionPerformed
        boolean p;
        Double a1, a2;
        int i = 0;

        String ss = jTextField1.getText();
        try {
            sc.con(ss);
        } catch (Exception exception) {
            this.jTextField2.setText("SYNTEX ERROR");
            return;
        }
        try {
            a1 = Double.parseDouble(JOptionPane.showInputDialog("Enter Starting point for analysis"));
            a2 = Double.parseDouble(JOptionPane.showInputDialog("Enter Ending point for analysis"));
        } catch (Exception exception) {
            return;
        }



        double x = 0, x1 = 0, y = 0, y1 = 0;
        String u = "";

        while (a1 < a2) {


            x = round(a1, 2);
            y = sc.con(ss, x);


            p = true;
            if (y == 0) {
                u = u + (++i) + " One root at X" + " = " + x + "\n";
                p = false;

            }
            if (p) {
                x1 = round((a1 + 0.01), 2);
                y1 = sc.con(ss, x1);

                if (y * y1 < 0) {
                    u = u + (++i) + " Root in" + " ( " + x + " , " + x1 + " )\n";

                }
            }
            a1 = a1 + 0.01;
        }

        ta.setText(u);
        gw2.setVisible(true);
    }//GEN-LAST:event_rootsActionPerformed

    private void differentiationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_differentiationActionPerformed
        double n;
        String ss = jTextField1.getText();
        try {
            sc.con(ss);
        } catch (Exception exception) {
            this.jTextField2.setText("SYNTEX ERROR");
            return;
        }
        try {
            n = Double.parseDouble(JOptionPane.showInputDialog("Enter Point"));

        } catch (Exception exception) {
            return;
        }


        double h = Math.abs(n * 0.00001);
        if (h == 0) {
            h = 0.00001;
        }
        double d = (sc.con(this.jTextField1.getText(), (n + h)) - sc.con(s.toString(), n)) / h;
        jTextField2.setText("" + round(d, xp) + " ");
    }//GEN-LAST:event_differentiationActionPerformed

    private void intergrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intergrationActionPerformed
        double n1 = 0, n2 = 0, l = 0, y = 0;
        double h = 0, j = 0;
        double d = 0;
        String ss = jTextField1.getText();
        try {
            sc.con(ss);
        } catch (Exception exception) {
            this.jTextField2.setText("SYNTEX ERROR");
            return;
        }
        try {
            n1 = Double.parseDouble(JOptionPane.showInputDialog("Enter Starting limit"));
            n2 = Double.parseDouble(JOptionPane.showInputDialog("Enter Ending limit"));

        } catch (Exception exception) {
            return;
        }


        y = 1000 * (n2 - n1);
        h = (double) (n2 - n1) / y;
        j = n1;

        while (l < y) {
            l++;
            j = j + h;
            d = d + (sc.con(ss, j) * h);
        }

        jTextField2.setText("" + round(d, xp) + " ");
    }//GEN-LAST:event_intergrationActionPerformed

    private void graphbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_graphbuttonActionPerformed
        String ss = jTextField1.getText();
        try {
            sc.con(ss);
            history.setText(history.getText() +"\n"+"GRAPH " +" (Y ="+ jTextField1.getText()+")");
        } catch (Exception exception) {
            this.jTextField2.setText("SYNTEX ERROR");
            return;
        }
        grafer.s = ss;
        gw.repaint();
        gw.setVisible(true);

      

      
    }//GEN-LAST:event_graphbuttonActionPerformed

    private void sigbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sigbuttonActionPerformed
        s = s.append("Sig");
        jTextField1.setText(s.toString());
    }//GEN-LAST:event_sigbuttonActionPerformed

    private void rembuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rembuttonActionPerformed
        s = s.append("Rem");
        jTextField1.setText(s.toString());
    }//GEN-LAST:event_rembuttonActionPerformed

    private void jButton56ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton56ActionPerformed
        JOptionPane.showMessageDialog(this, "WiCaDi The Scientific Calculator\nPowered By Java \nProgrammed by Semicolon;\n", " WiCaDi v1", 2);
    }//GEN-LAST:event_jButton56ActionPerformed

    private void pibuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pibuttonActionPerformed
        s = s.append("3.1415926535");
        jTextField1.setText(s.toString());
    }//GEN-LAST:event_pibuttonActionPerformed

    private void sinbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sinbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sinbuttonActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void clearhistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearhistoryActionPerformed
        history.setText(null);
    }//GEN-LAST:event_clearhistoryActionPerformed

    private void saveformulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveformulaActionPerformed
        String saveformula = jTextField1.getText();
        System.out.println(saveformula);
        
        String fname = (JOptionPane.showInputDialog("Enter Your Formula Name"));
        
        JFileChooser jfc = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());
        jfc.setDialogTitle("Choose a directory to save your file: ");
        jfc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int returnValue = jfc.showSaveDialog(null);
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            if (jfc.getSelectedFile().isDirectory()) {
                System.out.println("You selected the directory: " + jfc.getSelectedFile());
            }
        }
        try{
            FileWriter fw=new FileWriter(jfc.getSelectedFile()+"\\"+fname+".txt");
            fw.write(saveformula);
            fw.close();
        }catch(Exception e){System.out.println(e);}
        System.out.println("Success...");
    }//GEN-LAST:event_saveformulaActionPerformed

    private void loadformulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadformulaActionPerformed
        JFileChooser fc = new JFileChooser();
        JFrame frame = new JFrame();
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
       
            int returnVal = fc.showOpenDialog(frame);
            if (returnVal == JFileChooser.APPROVE_OPTION) {
              File file = fc.getSelectedFile();
              try {
                BufferedReader input = new BufferedReader(new InputStreamReader(
                    new FileInputStream(file)));
                jTextField1.read(input, "READING FILE");
              } catch (Exception e) {
                e.printStackTrace();
              }
            } else {
              System.out.println("Operation is CANCELLED");
            }
     
    }//GEN-LAST:event_loadformulaActionPerformed

  
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                MAIN m = new MAIN();

              
                m.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton answerbutton;
    private javax.swing.JButton arcbutton;
    private javax.swing.JButton arsbutton;
    private javax.swing.JButton artbutton;
    private javax.swing.JButton clearbutton;
    private javax.swing.JButton clearhistory;
    private javax.swing.JButton clearsavebutton;
    private javax.swing.JButton closebracket;
    private javax.swing.JButton cosbutton;
    private javax.swing.JButton deletebutton;
    private javax.swing.JButton differentiation;
    private javax.swing.JButton dividebutton;
    private javax.swing.JButton dotdutton;
    private javax.swing.JButton expbutton;
    private javax.swing.JButton graphbutton;
    private javax.swing.JTextArea history;
    private javax.swing.JButton intergration;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton48;
    private javax.swing.JButton jButton56;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JButton lnbutton;
    private javax.swing.JButton loadbutton;
    private javax.swing.JButton loadformula;
    private javax.swing.JButton logbutton;
    private javax.swing.JButton minusbutton;
    private javax.swing.JButton mulltiplybutton;
    private javax.swing.JButton number0btn;
    private javax.swing.JButton number1btn;
    private javax.swing.JButton number2btn;
    private javax.swing.JButton number3btn;
    private javax.swing.JButton number4btn;
    private javax.swing.JButton number5btn;
    private javax.swing.JButton number6btn;
    private javax.swing.JButton number7btn;
    private javax.swing.JButton number8btn;
    private javax.swing.JButton number9btn;
    private javax.swing.JButton openbracket;
    private javax.swing.JButton pibutton;
    private javax.swing.JButton plusbutton;
    private javax.swing.JButton powerbutton;
    private javax.swing.JButton rembutton;
    private javax.swing.JButton roots;
    private javax.swing.JButton savebutton;
    private javax.swing.JButton saveformula;
    private javax.swing.JButton sigbutton;
    private javax.swing.JButton sinbutton;
    private javax.swing.JButton sqrtbutton;
    private javax.swing.JButton stepbutton;
    private javax.swing.JButton tanbutton;
    private javax.swing.JButton valueofx;
    private javax.swing.JButton xbutton;
    // End of variables declaration//GEN-END:variables
}
