/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package wicadi.beta;

import java.awt.Dimension;
import java.awt.Frame;
import java.awt.Insets;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.HashMap;
import java.util.LinkedList;
import java.util.Map;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.filechooser.FileSystemView;

/**
 *
 * @author Kalana Hettiarachchi
 */
public class WiCaDiBeta extends javax.swing.JFrame {

    StringBuffer s;
    Random r;
    sc4 sc;
    double zx = 0;
    JFrame gw;
    JFrame gw2;
    JTextArea ta;
    grafer grf;
    roundnumber rn = new roundnumber();
    private int xp = 5; //default decimal points
    Map<String, String> formulaMap = new HashMap<>();
    
    int xMouse;
    int yMouse;

    /**
     * Creates new form WiCaDiMain
     */
    public WiCaDiBeta() {
        

        
        sc = new sc4();
        r = new Random();
        s = new StringBuffer();

        gw = new JFrame("Graph");
        gw2 = new JFrame();
        gw.setBounds(100, 100, 500, 500);
        gw2.setBounds(100, 100, 500, 500);
        ta = new JTextArea();
        JScrollPane pp = new JScrollPane();
        pp.setViewportView(ta);
        gw2.getContentPane().add(pp);
        grf = new grafer();
        gw.setContentPane(grf);

        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        DIFFERENTIATION = new javax.swing.JButton();
        DEFINITEINTEGRATION = new javax.swing.JButton();
        INDEFINITEINTEGRATION = new javax.swing.JButton();
        valueofx = new javax.swing.JButton();
        graph = new javax.swing.JButton();
        pixelperinch = new javax.swing.JButton();
        center = new javax.swing.JButton();
        gridstatus = new javax.swing.JCheckBox();
        loadformula = new javax.swing.JButton();
        saveformula = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        answer = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        plus = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        btn7 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        clearhistory = new javax.swing.JButton();
        historylist = new java.awt.List();
        tempformulalist = new java.awt.List();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        clearhistory1 = new javax.swing.JButton();
        minus = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        divide = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        display1 = new javax.swing.JTextField();
        display2 = new javax.swing.JTextField();
        save = new javax.swing.JButton();
        load = new javax.swing.JButton();
        del = new javax.swing.JButton();
        clr = new javax.swing.JButton();
        step = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        multiply = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        dot = new javax.swing.JButton();
        agraph = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        sin = new javax.swing.JButton();
        cos = new javax.swing.JButton();
        tan = new javax.swing.JButton();
        abs = new javax.swing.JButton();
        rem = new javax.swing.JButton();
        openbracket = new javax.swing.JButton();
        ars = new javax.swing.JButton();
        arc = new javax.swing.JButton();
        art = new javax.swing.JButton();
        sig = new javax.swing.JButton();
        closebracket = new javax.swing.JButton();
        varx = new javax.swing.JButton();
        pi = new javax.swing.JButton();
        power = new javax.swing.JButton();
        ln = new javax.swing.JButton();
        sqrt = new javax.swing.JButton();
        exp = new javax.swing.JButton();
        log = new javax.swing.JButton();
        vary = new javax.swing.JButton();
        varz = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        DIFFERENTIATION.setBackground(new java.awt.Color(0, 102, 102));
        DIFFERENTIATION.setForeground(new java.awt.Color(255, 255, 255));
        DIFFERENTIATION.setText("DIFFERENTIATION");
        DIFFERENTIATION.setToolTipText("Differentiate a formula");
        DIFFERENTIATION.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DIFFERENTIATIONActionPerformed(evt);
            }
        });

        DEFINITEINTEGRATION.setBackground(new java.awt.Color(0, 102, 102));
        DEFINITEINTEGRATION.setForeground(new java.awt.Color(255, 255, 255));
        DEFINITEINTEGRATION.setText("DEFINITE INTEGRATION");
        DEFINITEINTEGRATION.setToolTipText("Find the area under a curve");
        DEFINITEINTEGRATION.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DEFINITEINTEGRATIONActionPerformed(evt);
            }
        });

        INDEFINITEINTEGRATION.setBackground(new java.awt.Color(0, 102, 102));
        INDEFINITEINTEGRATION.setForeground(new java.awt.Color(255, 255, 255));
        INDEFINITEINTEGRATION.setText("INDEFINITE INTEGRATION");
        INDEFINITEINTEGRATION.setToolTipText("Find the indefinite integral of a formula");

        valueofx.setBackground(new java.awt.Color(0, 102, 102));
        valueofx.setForeground(new java.awt.Color(255, 255, 255));
        valueofx.setText("EVALUATE FORMULA");
        valueofx.setToolTipText("Evaluate a formula");
        valueofx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valueofxActionPerformed(evt);
            }
        });

        graph.setBackground(new java.awt.Color(153, 153, 0));
        graph.setText("<html><center>BASIC<br> GRAPHING</center></html>");
        graph.setToolTipText("Graphing a single variable formula");
        graph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                graphActionPerformed(evt);
            }
        });

        pixelperinch.setBackground(new java.awt.Color(153, 153, 0));
        pixelperinch.setText("PIX");
        pixelperinch.setToolTipText("Click to define how many pixels per unit in a graph");
        pixelperinch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pixelperinchActionPerformed(evt);
            }
        });

        center.setBackground(new java.awt.Color(153, 153, 0));
        center.setText("CENTER");
        center.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                centerActionPerformed(evt);
            }
        });

        gridstatus.setBackground(new java.awt.Color(153, 153, 0));
        gridstatus.setForeground(new java.awt.Color(255, 255, 255));
        gridstatus.setText("GRID");
        gridstatus.setToolTipText("Select to show graph in a grid");
        gridstatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gridstatusActionPerformed(evt);
            }
        });

        loadformula.setBackground(new java.awt.Color(206, 206, 30));
        loadformula.setText("LOAD FORMULA FILE");
        loadformula.setToolTipText("Click to load formula from a file");
        loadformula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadformulaActionPerformed(evt);
            }
        });

        saveformula.setBackground(new java.awt.Color(206, 206, 30));
        saveformula.setText("SAVE FORMULA FILE");
        saveformula.setToolTipText("Click to save formula/graph to a file");
        saveformula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveformulaActionPerformed(evt);
            }
        });

        btn1.setBackground(new java.awt.Color(204, 255, 153));
        btn1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btn1.setText("1");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        answer.setBackground(new java.awt.Color(9, 135, 9));
        answer.setForeground(new java.awt.Color(255, 255, 255));
        answer.setText("ANS");
        answer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerActionPerformed(evt);
            }
        });

        btn6.setBackground(new java.awt.Color(204, 255, 153));
        btn6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btn6.setText("6");
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });

        plus.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        plus.setText("+");
        plus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusActionPerformed(evt);
            }
        });

        btn2.setBackground(new java.awt.Color(204, 255, 153));
        btn2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btn2.setText("2");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btn7.setBackground(new java.awt.Color(204, 255, 153));
        btn7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btn7.setText("7");
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("History");

        clearhistory.setBackground(new java.awt.Color(181, 56, 56));
        clearhistory.setForeground(new java.awt.Color(255, 255, 255));
        clearhistory.setText("CLEAR HISTORY");
        clearhistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearhistoryActionPerformed(evt);
            }
        });

        historylist.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        historylist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                historylistMouseClicked(evt);
            }
        });
        historylist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historylistActionPerformed(evt);
            }
        });

        tempformulalist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tempformulalistMouseClicked(evt);
            }
        });

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Tempory Formula Storage");

        clearhistory1.setBackground(new java.awt.Color(181, 56, 56));
        clearhistory1.setForeground(new java.awt.Color(255, 255, 255));
        clearhistory1.setText("CLEAR TEMPORY FORMULA STORAGE");
        clearhistory1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearhistory1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tempformulalist, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator4)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(clearhistory, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
                            .addComponent(clearhistory1, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
                            .addComponent(historylist, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(14, 14, 14))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(9, 9, 9)
                .addComponent(tempformulalist, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clearhistory1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(historylist, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clearhistory)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        minus.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        minus.setText("-");
        minus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minusActionPerformed(evt);
            }
        });

        btn9.setBackground(new java.awt.Color(204, 255, 153));
        btn9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btn9.setText("9");
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });

        divide.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        divide.setText("/");
        divide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divideActionPerformed(evt);
            }
        });

        btn3.setBackground(new java.awt.Color(204, 255, 153));
        btn3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btn3.setText("3");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        btn8.setBackground(new java.awt.Color(204, 255, 153));
        btn8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btn8.setText("8");
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });

        display1.setBackground(new java.awt.Color(204, 204, 204));
        display1.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        display1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        display2.setBackground(new java.awt.Color(204, 204, 204));
        display2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        display2.setForeground(new java.awt.Color(0, 0, 0));
        display2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        save.setBackground(new java.awt.Color(14, 96, 180));
        save.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        save.setForeground(new java.awt.Color(255, 255, 255));
        save.setText("SAVE");
        save.setToolTipText("Save to clipboard");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        load.setBackground(new java.awt.Color(14, 96, 180));
        load.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        load.setForeground(new java.awt.Color(255, 255, 255));
        load.setText("LOAD");
        load.setToolTipText("Load from clipboard");
        load.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadActionPerformed(evt);
            }
        });

        del.setBackground(new java.awt.Color(181, 56, 56));
        del.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        del.setForeground(new java.awt.Color(255, 255, 255));
        del.setText("DEL");
        del.setToolTipText("backspace");
        del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delActionPerformed(evt);
            }
        });

        clr.setBackground(new java.awt.Color(194, 126, 25));
        clr.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        clr.setForeground(new java.awt.Color(255, 255, 255));
        clr.setText("CLR");
        clr.setToolTipText("Clear screen");
        clr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clrActionPerformed(evt);
            }
        });

        step.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        step.setText("STEP");
        step.setToolTipText("Round off number ");
        step.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stepActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Calisto MT", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("WiCaDi ");

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setFont(new java.awt.Font("Eras Medium ITC", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("By Semicolon;");

        jButton1.setText("ABOUT US");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("X");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1)
                            .addComponent(jLabel2)))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton2))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        multiply.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        multiply.setText("*");
        multiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplyActionPerformed(evt);
            }
        });

        btn4.setBackground(new java.awt.Color(204, 255, 153));
        btn4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btn4.setText("4");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        btn0.setBackground(new java.awt.Color(204, 255, 153));
        btn0.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btn0.setText("0");
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });

        dot.setBackground(new java.awt.Color(204, 255, 153));
        dot.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        dot.setText(".");
        dot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dotActionPerformed(evt);
            }
        });

        agraph.setBackground(new java.awt.Color(153, 153, 0));
        agraph.setText("<html><center>ADVANCED<br>GRAPHING</center>   </html>");
        agraph.setToolTipText("Quadratic, Rational, Exponential, Logarithemic, Sinusodial");
        agraph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agraphActionPerformed(evt);
            }
        });

        btn5.setBackground(new java.awt.Color(204, 255, 153));
        btn5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btn5.setText("5");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });

        sin.setBackground(new java.awt.Color(51, 0, 51));
        sin.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        sin.setForeground(new java.awt.Color(255, 255, 255));
        sin.setText("sin");
        sin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sinActionPerformed(evt);
            }
        });

        cos.setBackground(new java.awt.Color(51, 0, 51));
        cos.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        cos.setForeground(new java.awt.Color(255, 255, 255));
        cos.setText("cos");
        cos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cosActionPerformed(evt);
            }
        });

        tan.setBackground(new java.awt.Color(51, 0, 51));
        tan.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        tan.setForeground(new java.awt.Color(255, 255, 255));
        tan.setText("tan");
        tan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tanActionPerformed(evt);
            }
        });

        abs.setBackground(new java.awt.Color(51, 0, 51));
        abs.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        abs.setForeground(new java.awt.Color(255, 255, 255));
        abs.setText("abs");
        abs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                absActionPerformed(evt);
            }
        });

        rem.setBackground(new java.awt.Color(51, 0, 51));
        rem.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        rem.setForeground(new java.awt.Color(255, 255, 255));
        rem.setText("rem");
        rem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remActionPerformed(evt);
            }
        });

        openbracket.setBackground(new java.awt.Color(51, 0, 51));
        openbracket.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        openbracket.setForeground(new java.awt.Color(255, 255, 255));
        openbracket.setText("(");
        openbracket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openbracketActionPerformed(evt);
            }
        });

        ars.setBackground(new java.awt.Color(51, 0, 51));
        ars.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        ars.setForeground(new java.awt.Color(255, 255, 255));
        ars.setText("ars");
        ars.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arsActionPerformed(evt);
            }
        });

        arc.setBackground(new java.awt.Color(51, 0, 51));
        arc.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        arc.setForeground(new java.awt.Color(255, 255, 255));
        arc.setText("arc");
        arc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arcActionPerformed(evt);
            }
        });

        art.setBackground(new java.awt.Color(51, 0, 51));
        art.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        art.setForeground(new java.awt.Color(255, 255, 255));
        art.setText("art");
        art.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                artActionPerformed(evt);
            }
        });

        sig.setBackground(new java.awt.Color(51, 0, 51));
        sig.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        sig.setForeground(new java.awt.Color(255, 255, 255));
        sig.setText("sig");
        sig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sigActionPerformed(evt);
            }
        });

        closebracket.setBackground(new java.awt.Color(51, 0, 51));
        closebracket.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        closebracket.setForeground(new java.awt.Color(255, 255, 255));
        closebracket.setText(")");
        closebracket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closebracketActionPerformed(evt);
            }
        });

        varx.setBackground(new java.awt.Color(51, 0, 51));
        varx.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        varx.setForeground(new java.awt.Color(255, 255, 255));
        varx.setText("x");
        varx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varxActionPerformed(evt);
            }
        });

        pi.setBackground(new java.awt.Color(51, 0, 51));
        pi.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        pi.setForeground(new java.awt.Color(255, 255, 255));
        pi.setText("π");
        pi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                piActionPerformed(evt);
            }
        });

        power.setBackground(new java.awt.Color(51, 0, 51));
        power.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        power.setForeground(new java.awt.Color(255, 255, 255));
        power.setText("^");
        power.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                powerActionPerformed(evt);
            }
        });

        ln.setBackground(new java.awt.Color(51, 0, 51));
        ln.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        ln.setForeground(new java.awt.Color(255, 255, 255));
        ln.setText("ln");
        ln.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnActionPerformed(evt);
            }
        });

        sqrt.setBackground(new java.awt.Color(51, 0, 51));
        sqrt.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        sqrt.setForeground(new java.awt.Color(255, 255, 255));
        sqrt.setText("√");
        sqrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sqrtActionPerformed(evt);
            }
        });

        exp.setBackground(new java.awt.Color(51, 0, 51));
        exp.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        exp.setForeground(new java.awt.Color(255, 255, 255));
        exp.setText("exp");
        exp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expActionPerformed(evt);
            }
        });

        log.setBackground(new java.awt.Color(51, 0, 51));
        log.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        log.setForeground(new java.awt.Color(255, 255, 255));
        log.setText("log");
        log.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logActionPerformed(evt);
            }
        });

        vary.setBackground(new java.awt.Color(51, 0, 51));
        vary.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        vary.setForeground(new java.awt.Color(255, 255, 255));
        vary.setText("y");
        vary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varyActionPerformed(evt);
            }
        });

        varz.setBackground(new java.awt.Color(51, 0, 51));
        varz.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        varz.setForeground(new java.awt.Color(255, 255, 255));
        varz.setText("z");
        varz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varzActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(display1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(save, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(load, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(del, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                                    .addComponent(clr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(step, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(saveformula, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                                    .addComponent(loadformula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btn1, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                                            .addComponent(btn7, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                                            .addComponent(btn4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btn2, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                                            .addComponent(btn8, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                                            .addComponent(btn5, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)))
                                    .addComponent(btn0, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btn3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                                    .addComponent(btn6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                                    .addComponent(btn9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                                    .addComponent(dot, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(minus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                                    .addComponent(plus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                                    .addComponent(divide, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                                    .addComponent(multiply, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(42, 42, 42)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(pixelperinch, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(center, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(graph, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(agraph, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(52, 52, 52)
                                        .addComponent(gridstatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(111, 111, 111))))
                            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 495, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(sin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                                    .addComponent(cos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                                    .addComponent(tan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                                    .addComponent(abs, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                                    .addComponent(rem, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                                    .addComponent(varx, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(openbracket, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                                            .addComponent(ars, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                                            .addComponent(arc, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                                            .addComponent(art, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                                            .addComponent(sig, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(closebracket, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                                            .addComponent(pi, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                                            .addComponent(power, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                                            .addComponent(ln, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                                            .addComponent(exp, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(sqrt, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                                            .addComponent(answer, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                                            .addComponent(log, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(vary, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(varz, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                                        .addGap(63, 63, 63)))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(DEFINITEINTEGRATION, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                                    .addComponent(INDEFINITEINTEGRATION, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                                    .addComponent(DIFFERENTIATION, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                                    .addComponent(valueofx, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)))
                            .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 495, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(274, 274, 274)
                                .addComponent(display2, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 495, Short.MAX_VALUE))
                        .addGap(36, 36, 36)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {agraph, center, graph, pixelperinch});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(display1, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(display2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(save, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(load, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                                    .addComponent(clr, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(step, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                                    .addComponent(loadformula, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                                    .addComponent(del, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(saveformula, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(btn7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btn8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btn9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(plus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(98, 98, 98))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(46, 46, 46)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(btn5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btn4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btn6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(minus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(btn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btn3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(divide, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(6, 6, 6))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(graph, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(agraph, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pixelperinch, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(center, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(gridstatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(1, 1, 1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(dot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(multiply, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(btn0, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.DEFAULT_SIZE, 16, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(sin, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cos, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tan, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(abs, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rem, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(vary, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                                    .addComponent(varz, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                                    .addComponent(varx, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(sqrt, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                                        .addGap(10, 10, 10))
                                    .addComponent(valueofx, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(DIFFERENTIATION, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(DEFINITEINTEGRATION, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(INDEFINITEINTEGRATION, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                                .addGap(6, 6, 6))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(closebracket, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                                .addGap(205, 205, 205))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(openbracket, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ars, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                                    .addComponent(exp, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                                    .addComponent(log, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(arc, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                                            .addComponent(pi, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(art, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                                            .addComponent(power, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(sig, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                                            .addComponent(ln, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                                        .addGap(41, 41, 41))
                                    .addComponent(answer, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE))))
                        .addGap(30, 30, 30))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {agraph, center, graph, pixelperinch});

        graph.getAccessibleContext().setAccessibleDescription("");
        pixelperinch.getAccessibleContext().setAccessibleDescription("");
        center.getAccessibleContext().setAccessibleDescription("");
        gridstatus.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void varzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varzActionPerformed
        s = s.append("z");
        display1.setText(s.toString());
    }//GEN-LAST:event_varzActionPerformed

    private void varyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varyActionPerformed
        s = s.append("y");
        display1.setText(s.toString());
    }//GEN-LAST:event_varyActionPerformed

    private void logActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logActionPerformed
        s = s.append("Log");
        display1.setText(s.toString());
    }//GEN-LAST:event_logActionPerformed

    private void expActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expActionPerformed
        s = s.append("ep");
        display1.setText(s.toString());
    }//GEN-LAST:event_expActionPerformed

    private void sqrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sqrtActionPerformed
        s = s.append("√");
        display1.setText("√");
    }//GEN-LAST:event_sqrtActionPerformed

    private void lnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnActionPerformed
        s = s.append("ln");
        display1.setText(s.toString());
    }//GEN-LAST:event_lnActionPerformed

    private void powerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_powerActionPerformed
        s = s.append("^");
        display1.setText(s.toString());
    }//GEN-LAST:event_powerActionPerformed

    private void piActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_piActionPerformed
        s = s.append("3.1415926535");
        display1.setText(s.toString());
    }//GEN-LAST:event_piActionPerformed

    private void varxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varxActionPerformed
        s = s.append("x");
        display1.setText(s.toString());
    }//GEN-LAST:event_varxActionPerformed

    private void closebracketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closebracketActionPerformed
        s = s.append(")");
        display1.setText(s.toString());
    }//GEN-LAST:event_closebracketActionPerformed

    private void sigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sigActionPerformed
        s = s.append("Sig");
        display1.setText(s.toString());
    }//GEN-LAST:event_sigActionPerformed

    private void artActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_artActionPerformed
        s = s.append("Art");
        display1.setText(s.toString());
    }//GEN-LAST:event_artActionPerformed

    private void arcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arcActionPerformed
        s = s.append("Arc");
        display1.setText(s.toString());
    }//GEN-LAST:event_arcActionPerformed

    private void arsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arsActionPerformed
        s = s.append("Ars");
        display1.setText(s.toString());
    }//GEN-LAST:event_arsActionPerformed

    private void openbracketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openbracketActionPerformed
        s = s.append("(");
        display1.setText(s.toString());
    }//GEN-LAST:event_openbracketActionPerformed

    private void remActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remActionPerformed
        s = s.append("Rem");
        display1.setText(s.toString());
    }//GEN-LAST:event_remActionPerformed

    private void absActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_absActionPerformed
        s = s.append("Abs");
        display1.setText(s.toString());
    }//GEN-LAST:event_absActionPerformed

    private void tanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tanActionPerformed
        s = s.append("Tan");
        display1.setText(s.toString());
    }//GEN-LAST:event_tanActionPerformed

    private void cosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cosActionPerformed
        s = s.append("Cos");
        display1.setText(s.toString());
    }//GEN-LAST:event_cosActionPerformed

    private void sinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sinActionPerformed
        s = s.append("Sin");
        display1.setText(s.toString());
    }//GEN-LAST:event_sinActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        s = s.append("5");
        display1.setText(s.toString());
    }//GEN-LAST:event_btn5ActionPerformed

    private void agraphActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agraphActionPerformed
        Graph gc = new Graph();
        try {
            gc.agraphrun();
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_agraphActionPerformed

    private void dotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dotActionPerformed
        s = s.append(".");
        display1.setText(s.toString());
    }//GEN-LAST:event_dotActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        s = s.append("0");
        display1.setText(s.toString());
    }//GEN-LAST:event_btn0ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        s = s.append("4");
        display1.setText(s.toString());
    }//GEN-LAST:event_btn4ActionPerformed

    private void multiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplyActionPerformed
        s = s.append("*");
        display1.setText(s.toString());
    }//GEN-LAST:event_multiplyActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JOptionPane.showMessageDialog(this, "WiCaDi The Scientific Calculator \nProgrammed by © Semicolon;\n\n-Kalana Hettiarachchi\n-Kasun Yapa\n-Anuradha Senanayake\n-Rashmila Dharmage\n-Uvindu Dharmawardana\n\n", " WiCaDi v1", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void stepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stepActionPerformed
        try {
            xp = Integer.parseInt(JOptionPane.showInputDialog("Enter no. of digits after decimal point\n(Active from next operation)"));
            answer.doClick();
        } catch (Exception exception) {
            return;
        }
    }//GEN-LAST:event_stepActionPerformed

    private void clrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clrActionPerformed
        s.delete(0, s.length());
        display1.setText("0");
        display2.setText("");
    }//GEN-LAST:event_clrActionPerformed

    private void delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delActionPerformed
        if (s.length() > 0) {
            s.deleteCharAt(s.length() - 1);
            display1.setText(s.toString());
        }
    }//GEN-LAST:event_delActionPerformed

    private void loadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadActionPerformed
        String formulanam = JOptionPane.showInputDialog(null, "Enter the formula name", "Enter your formula name", JOptionPane.INFORMATION_MESSAGE);
        if (formulaMap.get(formulanam) == null) {
            JOptionPane.showMessageDialog(this, "There is no formula named " + formulanam + "!", "Error!", JOptionPane.ERROR_MESSAGE);
        } else {
            display1.setText(formulaMap.get(formulanam));
        }
        //System.out.println(formulaMap.get(formulanam));
    }//GEN-LAST:event_loadActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        String formulaname = JOptionPane.showInputDialog(null, "Enter formula name", "Enter your formula name", JOptionPane.INFORMATION_MESSAGE);
        String form = display1.getText();

        if (!formulaMap.containsKey(formulaname)) {
            formulaMap.put(formulaname, form);
            display1.setText(null);
            tempformulalist.add(form);

        } else {
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog(null, "Would you like to overwrite " + formulaname, "Warning", dialogButton);
            if (dialogResult == JOptionPane.YES_OPTION) {
                formulaMap.replace(formulaname, form);
                display1.setText(null);
            }
        }
        //System.out.println(formulaMap.get(formulaname));
    }//GEN-LAST:event_saveActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        s = s.append("8");
        display1.setText(s.toString());
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        s = s.append("3");
        display1.setText(s.toString());
    }//GEN-LAST:event_btn3ActionPerformed

    private void divideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divideActionPerformed
        s = s.append("/");
        display1.setText(s.toString());
    }//GEN-LAST:event_divideActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        s = s.append("9");
        display1.setText(s.toString());
    }//GEN-LAST:event_btn9ActionPerformed

    private void minusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minusActionPerformed
        s = s.append("-");
        display1.setText(s.toString());
    }//GEN-LAST:event_minusActionPerformed

    private void clearhistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearhistoryActionPerformed
        historylist.clear();
    }//GEN-LAST:event_clearhistoryActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        s = s.append("7");
        display1.setText(s.toString());
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        s = s.append("2");
        display1.setText(s.toString());
    }//GEN-LAST:event_btn2ActionPerformed

    private void plusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusActionPerformed
        s = s.append("+");
        display1.setText(s.toString());
    }//GEN-LAST:event_plusActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        s = s.append("6");
        display1.setText(s.toString());
    }//GEN-LAST:event_btn6ActionPerformed

    private void answerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerActionPerformed
        try {

            double d = rn.round(sc.con(this.display1.getText(), zx), xp);
            display2.setText("" + d + " ");

//            history.setText(history.getText() + "\n" + display1.getText() + " = " + display2.getText());
            historylist.add(display1.getText() + " = " + display2.getText());

        } catch (Exception dd) {
            display2.setText("SYNTAX ERROR");

        }
    }//GEN-LAST:event_answerActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        s = s.append("1");
        display1.setText(s.toString());
    }//GEN-LAST:event_btn1ActionPerformed

    private void saveformulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveformulaActionPerformed
        String saveformula = display1.getText();
        System.out.println(saveformula);

        String fname = (JOptionPane.showInputDialog("Enter Your Formula Name"));

        JFileChooser jfc = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());
        jfc.setDialogTitle("Choose a directory to save your file: ");
        jfc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int returnValue = jfc.showSaveDialog(null);
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            if (jfc.getSelectedFile().isDirectory()) {
                System.out.println("You selected the directory: " + jfc.getSelectedFile());
            }
        }
        try {
            FileWriter fw = new FileWriter(jfc.getSelectedFile() + "\\" + fname + ".txt");
                fw.write(saveformula);
                fw.close();
            } catch (Exception e) {
                System.out.println(e);
            }
            System.out.println("Success...");
    }//GEN-LAST:event_saveformulaActionPerformed

    private void loadformulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadformulaActionPerformed
        String userhome = System.getProperty("user.home");
        JFileChooser fc = new JFileChooser(userhome + "\\Desktop");
        FileNameExtensionFilter filter = new FileNameExtensionFilter("TEXT FILES", "txt", "text");
        fc.setFileFilter(filter);
        JFrame frame = new JFrame();
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        int returnVal = fc.showOpenDialog(frame);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();
            try {
                BufferedReader input = new BufferedReader(new InputStreamReader(
                    new FileInputStream(file)));
            display1.read(input, "READING FILE");
        } catch (Exception e) {
            e.printStackTrace();
        }
        } else {
            System.out.println("Operation is CANCELLED");
        }
    }//GEN-LAST:event_loadformulaActionPerformed

    private void gridstatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gridstatusActionPerformed
        if (this.gridstatus.isSelected()) {
            grafer.p = true;
        } else {
            grafer.p = false;
        }
    }//GEN-LAST:event_gridstatusActionPerformed

    private void centerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_centerActionPerformed
        try {
            grafer.ofx = Double.parseDouble(JOptionPane.showInputDialog("Enter centre point x cordinate"));
            grafer.ofy = Double.parseDouble(JOptionPane.showInputDialog("Enter centre point y cordinate"));

        } catch (Exception exception) {
            return;
        }
    }//GEN-LAST:event_centerActionPerformed

    private void pixelperinchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pixelperinchActionPerformed
        try {
            int n = Integer.parseInt(JOptionPane.showInputDialog("Enter n - no of Pixel per unit\n 0<n<2000"));
            if (!(n > 0 && n < 2000)) {
                throw new Exception();
            }
            grafer.k = n;
        } catch (Exception exception) {
            return;
        }
    }//GEN-LAST:event_pixelperinchActionPerformed
    
    private void graphActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_graphActionPerformed
        String ss = display1.getText();
        try {
            sc.con(ss);
//            history.setText(history.getText() + "\n" + "GRAPH " + " (Y =" + display1.getText() + ")");
            historylist.add("GRAPH " + " (Y =" + display1.getText() + ")");
        } catch (Exception exception) {
            this.display2.setText("SYNTAX ERROR");

            return;
        }
        gw.setTitle("Graph = " + display1.getText());
        grafer.s = ss;
        gw.repaint();
        gw.setVisible(true);
    }//GEN-LAST:event_graphActionPerformed

    private void valueofxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valueofxActionPerformed
        try {
            zx = Double.parseDouble(JOptionPane.showInputDialog(null, "Enter X", "Input value of X", 2));
        } catch (Exception exception) {
            return;
        }

        this.answer.doClick();
    }//GEN-LAST:event_valueofxActionPerformed

    private void DEFINITEINTEGRATIONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DEFINITEINTEGRATIONActionPerformed
        double n1 = 0, n2 = 0, l = 0, y = 0;
        double h = 0, j = 0;
        double d = 0;
        String ss = display1.getText();
        try {
            sc.con(ss);
        } catch (Exception exception) {
            this.display2.setText("SYNTAX ERROR");
            return;
        }
        try {
            n1 = Double.parseDouble(JOptionPane.showInputDialog("Enter Starting limit"));
            n2 = Double.parseDouble(JOptionPane.showInputDialog("Enter Ending limit"));

        } catch (Exception exception) {
            return;
        }

        y = 1000 * (n2 - n1);
        h = (double) (n2 - n1) / y;
        j = n1;

        while (l < y) {
            l++;
            j = j + h;
            d = d + (sc.con(ss, j) * h);
        }

        display2.setText("" + rn.round(d, xp) + " ");
//        history.setText(history.getText() + "\n" + display1.getText() + " = " + display2.getText() + "Integartion ( " + n1 + "-" + n2 + " )");
    }//GEN-LAST:event_DEFINITEINTEGRATIONActionPerformed
    
    private void DIFFERENTIATIONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DIFFERENTIATIONActionPerformed
        double n;
        String ss = display1.getText();
        try {
            sc.con(ss);
        } catch (Exception exception) {
            this.display2.setText("SYNTAX ERROR");
            return;
        }
        try {
            n = Double.parseDouble(JOptionPane.showInputDialog("Enter Point"));

        } catch (Exception exception) {
            return;
        }

        double h = Math.abs(n * 0.00001);
        if (h == 0) {
            h = 0.00001;
        }
        double d = (sc.con(this.display1.getText(), (n + h)) - sc.con(s.toString(), n)) / h;
        display2.setText("" + rn.round(d, xp) + " ");
    }//GEN-LAST:event_DIFFERENTIATIONActionPerformed

    private void historylistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historylistActionPerformed
       
    }//GEN-LAST:event_historylistActionPerformed

    private void historylistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_historylistMouseClicked
        if(evt.getClickCount()==2){
            String ind = historylist.getSelectedItem();
            display1.setText(ind);
        }
    }//GEN-LAST:event_historylistMouseClicked

    private void tempformulalistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tempformulalistMouseClicked
        if(evt.getClickCount()==2){
            String formulaa = tempformulalist.getSelectedItem();
            display1.setText(formulaa);
        }
    }//GEN-LAST:event_tempformulalistMouseClicked

    private void clearhistory1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearhistory1ActionPerformed
        tempformulalist.clear();
    }//GEN-LAST:event_clearhistory1ActionPerformed

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xMouse, y-yMouse);
    }//GEN-LAST:event_formMouseDragged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WiCaDiBeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WiCaDiBeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WiCaDiBeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WiCaDiBeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WiCaDiBeta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DEFINITEINTEGRATION;
    private javax.swing.JButton DIFFERENTIATION;
    private javax.swing.JButton INDEFINITEINTEGRATION;
    private javax.swing.JButton abs;
    private javax.swing.JButton agraph;
    private javax.swing.JButton answer;
    private javax.swing.JButton arc;
    private javax.swing.JButton ars;
    private javax.swing.JButton art;
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton center;
    private javax.swing.JButton clearhistory;
    private javax.swing.JButton clearhistory1;
    private javax.swing.JButton closebracket;
    private javax.swing.JButton clr;
    private javax.swing.JButton cos;
    private javax.swing.JButton del;
    private javax.swing.JTextField display1;
    private javax.swing.JTextField display2;
    private javax.swing.JButton divide;
    private javax.swing.JButton dot;
    private javax.swing.JButton exp;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton graph;
    private javax.swing.JCheckBox gridstatus;
    private java.awt.List historylist;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JButton ln;
    private javax.swing.JButton load;
    private javax.swing.JButton loadformula;
    private javax.swing.JButton log;
    private javax.swing.JButton minus;
    private javax.swing.JButton multiply;
    private javax.swing.JButton openbracket;
    private javax.swing.JButton pi;
    private javax.swing.JButton pixelperinch;
    private javax.swing.JButton plus;
    private javax.swing.JButton power;
    private javax.swing.JButton rem;
    private javax.swing.JButton save;
    private javax.swing.JButton saveformula;
    private javax.swing.JButton sig;
    private javax.swing.JButton sin;
    private javax.swing.JButton sqrt;
    private javax.swing.JButton step;
    private javax.swing.JButton tan;
    private java.awt.List tempformulalist;
    private javax.swing.JButton valueofx;
    private javax.swing.JButton varx;
    private javax.swing.JButton vary;
    private javax.swing.JButton varz;
    // End of variables declaration//GEN-END:variables
}
